DECLARE @LANG_ID Int
DECLARE @LANGLABEL_ID Int

SET @LANG_ID = (SELECT LangPK FROM tblLanguages WHERE LangName='English')

SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Actions')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Actions')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Active')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Active')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Add')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Add')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Add_To_Knowledgebase')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Add To Knowledgebase')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Add-Ons')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Add-Ons')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Administration')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Administration')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Administration_Menu')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Administration Menu')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='All')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'All')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Alternate_Email')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Alternate Email')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Assigned')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Assigned')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Assigned_Rep')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Assigned Rep')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Assignment')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Assignment')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Assignment_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Assignment Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Assignments')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Assignments')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Attach')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Attach')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Attachments_Enabled')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Attachments Enabled')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Attach_Files')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Attach Files')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Authentication')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Authentication')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Authentication_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Authentication Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Between_Dates')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Between Dates')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Body')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Body')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Cancelled')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Cancelled')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Cancelled_Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Cancelled Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Criteria')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Criteria')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Detail')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Detail')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Options')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Options')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Submitted')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Submitted')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Type_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Type Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Types')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Types')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Case_Updated')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Case Updated')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Categories')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Categories')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Category')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Category')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Category_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Category Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Cause')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Cause')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Cc')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Cc')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='City')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'City')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Close')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Close')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Closed')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Closed')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Closed_Date')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Closed Date')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Closed_Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Closed Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contact')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contact')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contact_Detail')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contact Detail')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contact_Details')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contact Details')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contact_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contact Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contact_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contact Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Contacts')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Contacts')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Country')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Country')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Courier_Address')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Courier Address')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Custom')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Custom')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Date_Criteria')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Date Criteria')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Date_Format')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Date Format')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Default_Language')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Default Language')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Default_Priority')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Default Priority')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Default_Role')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Default Role')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Default_Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Default Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Department')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Department')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Department_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Department Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Departments')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Departments')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Description')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Description')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Detailed_Description')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Detailed Description')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Edit')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Edit')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Edit_My_Profile')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Edit My Profile')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Enabled')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Enabled')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Message')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Message')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Message_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Message Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Message_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Message Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Messages')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Messages')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Email_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Email Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Encoding')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Encoding')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Entered_By')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Entered By')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Entered_Date')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Entered Date')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Fax')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Fax')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='First_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'First Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='From')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'From')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Full_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Full Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Group')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Group')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Group_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Group Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Group_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Group Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Groups')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Groups')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='In/Out_Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'In/Out Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='In/Out_Status_Date')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'In/Out Status Date')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='In/Out_Status_Text')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'In/Out Status Text')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Is_Active')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Is Active')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Is_RTL')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Is RTL')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Is_User')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Is User')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='ISO_639')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'ISO 639')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Issue')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Issue')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Item_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Item Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Item_Order')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Item Order')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Items')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Items')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Items_Per_Page')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Items Per Page')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Job_Function')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Job Function')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Job_Title')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Job Title')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Keyword')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Keyword')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Keyword_Criteria')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Keyword Criteria')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Keywords')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Keywords')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Knowledgebase')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Knowledgebase')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Knowledgebase_Enabled')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Knowledgebase Enabled')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Knowledgebase_Record')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Knowledgebase Record')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Language')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Language')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Language_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Language Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Languages')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Languages')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Last_Updated')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Last Updated')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Last_Access_Time')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Last Access Time')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Last_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Last Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Last_Updated_By')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Last Updated By')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_All_Un-Assigned_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List All Un-Assigned Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Assigned_Cases_For')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Assigned Cases For')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Item')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Item')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Item_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Item Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Items')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Items')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_My_Active_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List My Active Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_My_Assigned_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List My Assigned Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_My_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List My Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='List_Unassigned_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'List Unassigned Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Lists')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Lists')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Localised')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Localised')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Location')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Location')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Log_Off')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Log Off')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Log_On')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Log On')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Logon')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Logon')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Mail_Address')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Mail Address')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Main_Menu')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Main Menu')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_&_Configure_System')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage & Configure System')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Assignments')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Assignments')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Case_Types')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Case Types')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Categories')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Categories')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Contacts')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Contacts')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Departments')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Departments')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Email_Messages')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Email Messages')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Groups')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Groups')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Languages')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Languages')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_List_Items')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage List Items')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Lists')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Lists')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Organisations')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Organisations')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Roles')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Roles')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Manage_Strings')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Manage Strings')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Max_Attachment_Size')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Max Attachment Size')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Members')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Members')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Assignment')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Assignment')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Case_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Case Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Category')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Category')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Contact')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Contact')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Department')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Department')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Email')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Email')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Email_Message')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Email Message')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Group')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Group')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_Language')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify Language')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Modify_List')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Modify List')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Assignment')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Assignment')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Case')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Case')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Category')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Category')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Contact')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Contact')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Department')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Department')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Email')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Email')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Email_Message')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Email Message')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_Knowledgebase_Record')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New Knowledgebase Record')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='New_User')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'New User')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Next')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Next')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='No')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'No')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Non_Members')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Non Members')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Note')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Note')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Notes')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Notes')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Notification_Settings')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Notification Settings')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Notify_User')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Notify User')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Office_Address')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Office Address')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='On_Behalf_Of')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'On Behalf Of')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Open')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Open')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Open_Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Open Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Options')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Options')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Or')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Or')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Order')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Order')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Order_By')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Order By')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Organisation')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Organisation')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Organisation_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Organisation Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Organisation_Short_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Organisation Short Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Organisation_Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Organisation Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Organisations')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Organisations')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Pager_Email')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Pager Email')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Password')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Password')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Pending')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Pending')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Permissions')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Permissions')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Phone')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Phone')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Phone_Home')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Phone (Home)')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Phone_Mobile')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Phone (Mobile)')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Phone_Work')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Phone (Work)')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Photo_File')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Photo File')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Photo_File_ID')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Photo File ID')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Previous')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Previous')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Primary_Contact')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Primary Contact')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Printer_Friendly_View')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Printer Friendly View')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Priority')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Priority')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Private_Note')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Private Note')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Raised_Date')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Raised Date')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Reference_ID')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Reference ID')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Register')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Register')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Remove')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Remove')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Reopen')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Reopen')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Rep')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Rep')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Rep_Group')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Rep Group')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Rep_Options')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Rep Options')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Report_Criteria')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Report Criteria')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Reports')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Reports')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Reports_Enabled')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Reports Enabled')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Reports_Menu')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Reports Menu')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Resolution')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Resolution')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Results')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Results')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Resume')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Resume')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Role')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Role')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Role_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Role Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Roles')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Roles')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Save')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Save')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search_Case_Archives')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search Case Archives')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search_Cases')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search Cases')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search_Knowledgebase')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search Knowledgebase')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search_Options')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search Options')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Search_Results')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Search Results')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Site_Information')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Site Information')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Site_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Site Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='SMTP_Server')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'SMTP Server')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Start_Date')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Start Date')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='State')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'State')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Status')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Status')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Status_Summary_Report')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Status Summary Report')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Subject')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Subject')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Submit')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Submit')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Submit_New_Case')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Submit New Case')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='System_Configuration')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'System Configuration')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='System_Configuration_Saved')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'System Configuration Saved')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='System_Defaults')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'System Defaults')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='System_Email_Address')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'System Email Address')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Through')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Through')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Time_Format')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Time Format')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Time_Spent')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Time Spent')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Timezone_Offset')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Timezone Offset')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Title')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Title')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='To')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'To')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Type')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Type')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Update')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Update')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='User_Name')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'User Name')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='User_Permissions')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'User Permissions')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Version')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Version')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View/Edit_Attachments')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View/Edit Attachments')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View_Case')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View Case')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View_Contact_Details')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View Contact Details')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View_License')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View License')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='View_Reports')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'View Reports')
SET @LANGLABEL_ID = (SELECT LangLabelPK FROM tblLanguageLabels WHERE LangLabel='Yes')	
	INSERT INTO tblLanguageTexts (LangFK, LangLabelFK, LangText) VALUES (@LANG_ID, @LANGLABEL_ID, 'Yes')
GO
